// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGuz_cjzDnczb0ZqmAxUhJxDZ8SiLQt3Y',
    appId: '1:387910483139:android:0d144a3bfaf5922c8cf676',
    messagingSenderId: '387910483139',
    projectId: 'authentication-fbab8',
    storageBucket: 'authentication-fbab8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCufQlFRRPNKGFWL9YJUMoa--GrJDiysrY',
    appId: '1:387910483139:ios:5b335a588bec4b018cf676',
    messagingSenderId: '387910483139',
    projectId: 'authentication-fbab8',
    storageBucket: 'authentication-fbab8.appspot.com',
    androidClientId: '387910483139-08sc0225b27konm68ollv1ij5247arm3.apps.googleusercontent.com',
    iosClientId: '387910483139-jsq38s91rl09jlnt6tndjckrvp63nplq.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );
}
